### PR TITLE
Add support for parenthesizing parameters: ${paramName}

### PR DESCRIPTION
**Pull request by noordawod**
... and on the way adjusted few long lines and added a comment to the top of the file about the nature of this file.

### CODE REVIEW

**Comment by noordawod** [comment]
@long1eu got some time to go over this?

**Comment by long1eu** [comment]
I'll try my best.

**Comment by noordawod** [comment]
@long1eu let me know if you need help with managing the plugin, I have some free time.

**Comment by noordawod** [comment]
@long1eu let me know if you need help with managing the plugin, I have some free time.

**Comment by noordawod** [comment]
@long1eu let me know if you need help with managing the plugin, I have some free time.

**Review by long1eu — CHANGES_REQUESTED** [review]
* the next version should increment the second value since the last value is for the IDE version
* the do-not-change message is a bit to much in my opinion

**Comment by long1eu** [comment]
I did them myself.

**Comment by noordawod** [comment]
I was at work, but good work! Thanks for the merge!

**Pull request merged**
