### PR TITLE
Adds support for matching locales with a country code.

### PR DESCRIPTION
**Pull request by noordawod**
This comes in handy with a single language being spoken in many countries, so instead of creating the same ARB file but with a different language/country designation, it's possible now to supply a true/false parameter to match such locales.

### CODE REVIEW

**Comment by noordawod** [comment]
@long1eu bumping.

**Comment by noordawod** [comment]
@long1eu bumping.

**Comment by ghost** [comment]
@long1eu so....?

**Comment by gregertw** [comment]
@long1eu , would be great if this PR is merged!

**Comment by noordawod** [comment]
@long1eu bump.

**Comment by long1eu** [comment]
Thank you for your patience.

**Comment by long1eu** [comment]
https://github.com/long1eu/flutter_i18n/releases/tag/v1.0

**Pull request merged**
