### PR TITLE
Fixes a breaking change in Flutter.

### PR DESCRIPTION
**Pull request by noordawod**
Apologies for the EOF :)

### CODE REVIEW

**Comment by noordawod** [comment]
I have also submitted a bugfix for Flutter as it also has a bug in its code regardless of this PR (https://github.com/flutter/flutter/pull/24481). Also, I'll compliment my PR so that `flutter_i18n` supports the new `localeListResolutionCallback` parameter which fixes the bug reported by many users.

**Comment by noordawod** [comment]
@long1eu 

Due to recent updates to Flutter, the plugin was unusable for me and, according to the reported bugs, others. So I've sat and invested few hours to fix it, and I hope you can release a new updated build next week. Thanks in advance!

**Comment by long1eu** [comment]
Thanks!

**Comment by noordawod** [comment]
Thank you! :)

**Comment by noordawod** [comment]
Hmm, JetBrains approved the plugin but compatibility is from 183.* onwards... Why? Isn't that the dev branch of Android Studio? I believe the plugin should target stable (181.*)... Any chance you can fix this, @long1eu?

**Comment by long1eu** [comment]
0.1.2 is for 2018.2(182.*) and 0.1.3(183.*)
They both contain the same thing. This is the approach that the Flutter plugin takes so I thought it make sense to do the same so we don't have any compatibility issues like we had before.

screen shot 2018-11-19 at 22 22 36
If you look here you can see that there are 3 versions of the Flutter plugin for the different platforms they target. The difference can be seen at the versioning number. 
30.0.**1**(18**1**.*) 
30.0.**2**(18**2**.*)
30.0.**3**(18**3**.*)

**Comment by noordawod** [comment]
Ohh nice!!! :) Sorry, didn't see that.

**Comment by long1eu** [comment]
No worries. It's good that you've asked.

**Comment by noordawod** [comment]
Okay, I don't know what I'm doing but I cannot see the `30.0.1` at all here: 
https://plugins.jetbrains.com/plugin/10128-flutter-i18n

What am I missing?

PS: My Android Studio is 3.2.1 (181.5540) and it also cannot find updates to this plugin.

**Comment by long1eu** [comment]
The image above is for the Flutter plugin. That was the example I started with. Do you really need 2018.1 ? Intellij didn't update the dart plugin for 2018.1 since may. This is why I dropped 2018.1 and kept only 2018.2 nad 2018.3

**Comment by noordawod** [comment]
Okay, I'm totally lost. Isn't this a Kotlin plugin for Android Studio?
Mind me asking, `The image above is for the Flutter plugin` – where is the plugin published if not on JetBrains?

**Comment by long1eu** [comment]
[i18n-0.1.1.jar.zip](https://github.com/long1eu/flutter_i18n/files/2597088/i18n-0.1.1.jar.zip)
does this work for you?

**Comment by long1eu** [comment]
you need to unzip it first

**Comment by noordawod** [comment]
Okay, that did the trick. Thanks!
So... do I need to compile and generate a .jar file? Or are you publishing the artifacts somewhere?

**Comment by long1eu** [comment]
I submitted this version as you said. I actually don't use Android Studio. Now it make sense why Flutter still supports version 2018.1 

I'll add all future release here so we can test them before publishing.
https://github.com/long1eu/flutter_i18n/releases/tag/v0.1

Thanks again for your support.

**Comment by noordawod** [comment]
Good idea!

By the way, 0.1.1 still doesn't include some commits I pushed, namely `isSupported()` and `getLang()` checking for null. Actually, on a second look, it doesn't include many of the commits. Maybe a newer release is due? :)

**Comment by long1eu** [comment]
All the commits from this PR are merged. Still I added some changes after that. Not sure if this include those methods.

**Comment by noordawod** [comment]
Okay. Something is not right then, maybe it's my setup.
Anyway, now my Android Studio stopped auto-generating the `lib/generated/i18n.dart` file whenever I change any of the ARB files. Hmm... What do you reckon is happening?

**Comment by long1eu** [comment]
can you give me the arb file?

**Comment by noordawod** [comment]
```
{
  "lang_name_en": "English",
  "lang_name_local": "English",

  "lang_or": "or",
  "lang_and": "and",

  "btn_save": "Save",
  "btn_save_changes": "Save changes",
  "btn_edit": "Edit",
  "btn_publish": "Upload",
  "btn_share": "Share",
  "btn_sure": "Sure!",
  "btn_yes": "Yes",
  "btn_no": "No",
  "btn_chat": "Chat",
  "btn_chat_with": "Chat with $name",
  "btn_back": "Back",
  "btn_retry": "Retry",
  "btn_try_again": "Try again",
  "btn_dismiss": "Dismiss",
  "btn_okay": "OK",
  "btn_okay_try": "OK, try now!",
  "btn_got_it": "Got it!",
  "btn_sounds_good": "Sounds good",
  "btn_maybe_later": "Maybe later",
  "btn_reset": "Reset",
  "btn_delete": "Delete",
  "btn_signout": "Signout",
  "btn_show": "Show",
  "btn_continue": "Continue",
  "btn_next": "Next"
}
```

But apart from updating the plugin in Android Studio, nothing changed really.

**Comment by noordawod** [comment]
Okay, Android Studio is barfing on restart with this trace:

```
No match found
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at java.util.regex.Matcher.group(Matcher.java:496)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator$appendPluralMethod$parameterName$1.invoke(I18nFileGenerator.kt:205)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator$appendPluralMethod$parameterName$1.invoke(I18nFileGenerator.kt:20)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.appendPluralMethod$i18n(I18nFileGenerator.kt:203)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.appendSClass(I18nFileGenerator.kt:87)
	at eu.long1.flutter.i18n.workers.I18nFileGenerator.generate(I18nFileGenerator.kt:42)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1$lambda$1.compute(actions.kt:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:917)
	at eu.long1.flutter.i18n.workers.Initializer$runActivity$$inlined$scheduleAtFixedRate$1.run(Timer.kt:146)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

Now at least we know why it's not generating the file.

**Comment by noordawod** [comment]
I will send you the arb file privately.

**Comment by long1eu** [comment]
this is my build version of Android Studio

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

It works on me. Can you check again that you've restarted the android studio.

**Comment by noordawod** [comment]
More or less the same here, but on Linux. I sent you a private Email with the arb file, try it out?

**Comment by noordawod** [comment]
The Flutter team has finally merged my fix for Locale being null in the engine: https://github.com/flutter/flutter/pull/24481

Seems like this bug is finally fixed, both for Flutter and for this plugin.

**Comment by long1eu** [comment]
Thanks again.

**Pull request merged**
