### PR TITLE
migrates project to use gradle and intellij plugins

### PR DESCRIPTION
**Pull request by juliocbcotta**
This PR migrates the project to gradle build system and uses intellij plugins.
I was able to build the plugin.
I was not able to fully test the results of the changes since I never developed a plugin before, but it may be a start point for you.

### CODE REVIEW

**Comment by long1eu** [comment]
Why should we go with gradle?

**Comment by juliocbcotta** [comment]
@long1eu Gradle is a build system that has been supported for the JetBrains/Intellij team.

Some advantages:

- Easy dependencies management (you can see that I removed the jar files and the dependencies are now listed in the dependencies bloc. It will download the given versions when building);
- Plugin system to extend build scripts ( in this case I used the official [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) to handle the intellij plugin configs files generation);
- Easy automation for build and testing (provides tasks for testing and publishing a new version);

**Comment by juliocbcotta** [comment]
Hey @long1eu, mind to explain why closing this pr? There are a lot of advantages with this migration and it seems that you barely wanted to discuss it.
That is a poor way to manage a open source project.

**Comment by long1eu** [comment]
You are right. I've closed it because I did my own migration based on this. I was waiting to find some time to handle all the new issues. I'm sorry for closing this. 

After I push my changes please make sure to give me your opinion. I'd love to change stuff if needed.

**Comment by long1eu** [comment]
I've pushed my changes, feel free to rebase and add any changes on another PR. Thanks again :D.

**Pull request closed without merging**
